# Bun Configuration for podAI Platform

[install]
cache = true
exact = false
lockfile = true
production = false
registry = "https://registry.npmjs.org/"

[install.scopes]
"@coral-xyz" = "https://registry.npmjs.org/"
"@solana" = "https://registry.npmjs.org/"
"@lightprotocol" = "https://registry.npmjs.org/"
"@metaplex-foundation" = "https://registry.npmjs.org/"

[test]
coverage = true
timeout = 30000

[run]
silent = false
env = ".env"

[build]
minify = false
sourcemap = "external"
target = "node"
format = "esm"


 