
import * as fs from 'fs';
import * as path from 'path';

// Path to IDL
const IDL_PATH = path.resolve(__dirname, '../../../target/idl/ghostspeak_marketplace.json');
const OUTPUT_PATH = path.resolve(__dirname, '../src/generated/instruction-mappings.ts');

interface IdlAccount {
  name: string;
  writable?: boolean;
  signer?: boolean;
  optional?: boolean;
  docs?: string[];
  address?: string;
  pda?: {
    seeds: unknown[];
  };
}

interface IdlInstruction {
  name: string;
  accounts: IdlAccount[];
  docs?: string[];
  discriminator?: number[];
  args?: unknown[];
}

interface Idl {
  instructions: IdlInstruction[];
}

function generateMappings() {
  console.log(`Reading IDL from: ${IDL_PATH}`);
  if (!fs.existsSync(IDL_PATH)) {
    console.error(`Error: IDL file not found at ${IDL_PATH}`);
    process.exit(1);
  }

  const idlContent = fs.readFileSync(IDL_PATH, 'utf8');
  const idl = JSON.parse(idlContent) as Idl;
  
  const instructionMap: Record<string, any> = {};
  
  const instructions = idl.instructions || [];
  
  for (const instruction of instructions) {
    const name = instruction.name;
    
    // Skip export instructions if needed, but IDL usually has snake_case
    // The previous code skipped '_export_', mimicking that
    if (name.startsWith('_export_')) {
      continue;
    }
    
    const accounts = instruction.accounts || [];
    const accountInfos = accounts.map((account: IdlAccount) => ({
      name: account.name,
      writable: account.writable ?? false,
      signer: account.signer ?? false,
      optional: account.optional ?? false,
      docs: account.docs ?? [],
      address: account.address,
      pda: account.pda
    }));
    
    instructionMap[name] = {
      name,
      expectedAccounts: accounts.map(a => ({ name: a.name, pda: !!a.pda })), // Simplified for ExpectedAccount
      accounts: accountInfos,
      docs: instruction.docs ? instruction.docs.join(' ') : '', // docs as string or array? instruction-error-handler expects docs property?
      // utils/instruction-error-handler.ts uses mapping.docs as string in createAccountMismatchError
      discriminator: instruction.discriminator || [],
      args: instruction.args || []
    };
  }

  const fileContent = `/**
 * This file is auto-generated by scripts/generate-mappings.ts
 * Do not edit this file manually.
 */

export interface AccountInfo {
  name: string;
  writable: boolean;
  signer: boolean;
  optional: boolean;
  docs: string[];
  address?: string;
  pda?: {
    seeds: unknown[];
  };
}

export interface ExpectedAccount {
  name: string;
  pda: boolean;
}

export interface InstructionMapping {
  name: string;
  expectedAccounts: ExpectedAccount[];
  accounts: AccountInfo[];
  docs?: string;
  discriminator: number[];
  args: unknown[];
}

export const instructionAccountMappings: Record<string, InstructionMapping> = ${JSON.stringify(instructionMap, null, 2)};
`;

  fs.writeFileSync(OUTPUT_PATH, fileContent);
  console.log(`Generated mappings at: ${OUTPUT_PATH}`);
}

generateMappings();
