[package]
name = "podai-sdk"
version = "0.1.0"
edition = "2021"
description = "Rust SDK for the podAI Agent Commerce Protocol"
license = "MIT"
repository = "https://github.com/ghostspeak/ghostspeak"
homepage = "https://ghostspeak.com"
documentation = "https://docs.rs/podai-sdk"
readme = "../README.md"
keywords = ["solana", "blockchain", "agent", "commerce", "web3"]
categories = ["api-bindings", "web-programming"]

[dependencies]
# Core Solana dependencies - align versions
solana-sdk = "2.3.1"
solana-client = "2.3.2"
solana-program = "2.3.0"

spl-token = "8.0.0"
spl-token-2022 = "9.0.0"
spl-associated-token-account = "7.0.0"

# Serialization - use consistent version
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
bincode = "1.3.3"
borsh = { version = "1.5.1", features = ["derive"] }
base64 = "0.22.1"

# Async and futures
tokio = { version = "1.45.1", features = ["full"] }
futures = "0.3.31"
futures-util = "0.3.31"

# Crypto and hashing
blake3 = "1.8.2"
bs58 = "0.5.1"

# Utility
chrono = { version = "0.4.41", features = ["serde"] }
thiserror = "2.0.12"
anyhow = "1.0.98"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
url = "2.5.4"

# HTTP client
reqwest = { version = "0.12.21", features = ["json", "rustls-tls"], default-features = false }

# Logging
log = "0.4.27"
env_logger = "0.11.8"
tracing = "0.1.41"

# Optional compression feature
light-poseidon = { version = "0.3.0", optional = true }

# New dependencies
hex = "0.4.3"
solana-transaction-status = "2.0.0"

[dev-dependencies]
tokio-test = "0.4.4"
solana-test-validator = "2.3.2"
fastrand = "2.0.2"

[[bench]]
name = "performance_benchmark"
harness = false

[features]
default = ["spl-token-2022"]
compression = ["light-poseidon"]
spl-token-2022 = []
testing = []

[lib]
name = "podai_sdk"
path = "src/lib.rs"

[[example]]
name = "enhanced_agent_registration"
path = "examples/enhanced_agent_registration.rs"
required-features = ["testing"] 