/**
 * Type declarations for lucide-react
 * 
 * This file helps TypeScript resolve lucide-react types when bun's
 * symlink-based node_modules causes resolution issues.
 */

declare module 'lucide-react' {
  import * as React from 'react'
  
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: string | number
    absoluteStrokeWidth?: boolean
  }
  
  export type LucideIcon = React.ForwardRefExoticComponent<
    Omit<LucideProps, 'ref'> & React.RefAttributes<SVGSVGElement>
  >
  
  // Common icons used in the project
  export const Search: LucideIcon
  export const Globe: LucideIcon
  export const Zap: LucideIcon
  export const TrendingUp: LucideIcon
  export const Activity: LucideIcon
  export const Filter: LucideIcon
  export const LayoutGrid: LucideIcon
  export const List: LucideIcon
  export const RefreshCw: LucideIcon
  export const ExternalLink: LucideIcon
  export const Shield: LucideIcon
  export const Clock: LucideIcon
  export const DollarSign: LucideIcon
  export const Users: LucideIcon
  export const Plus: LucideIcon
  export const Bot: LucideIcon
  export const ArrowLeft: LucideIcon
  export const Hash: LucideIcon
  export const Lock: LucideIcon
  export const MessageCircle: LucideIcon
  export const Volume2: LucideIcon
  export const Sparkles: LucideIcon
  export const Code: LucideIcon
  export const Copy: LucideIcon
  export const Check: LucideIcon
  export const Play: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronUp: LucideIcon
  export const ChevronLeft: LucideIcon
  export const X: LucideIcon
  export const Menu: LucideIcon
  export const Settings: LucideIcon
  export const Home: LucideIcon
  export const User: LucideIcon
  export const Mail: LucideIcon
  export const Send: LucideIcon
  export const Image: LucideIcon
  export const File: LucideIcon
  export const Folder: LucideIcon
  export const Trash: LucideIcon
  export const Edit: LucideIcon
  export const Save: LucideIcon
  export const Download: LucideIcon
  export const Upload: LucideIcon
  export const Link: LucideIcon
  export const Share: LucideIcon
  export const Heart: LucideIcon
  export const Star: LucideIcon
  export const Bell: LucideIcon
  export const Calendar: LucideIcon
  export const Map: LucideIcon
  export const Phone: LucideIcon
  export const Video: LucideIcon
  export const Music: LucideIcon
  export const Camera: LucideIcon
  export const Mic: LucideIcon
  export const Sun: LucideIcon
  export const Moon: LucideIcon
  export const Cloud: LucideIcon
  export const Wifi: LucideIcon
  export const Battery: LucideIcon
  export const Power: LucideIcon
  export const AlertCircle: LucideIcon
  export const AlertTriangle: LucideIcon
  export const Info: LucideIcon
  export const HelpCircle: LucideIcon
  export const Eye: LucideIcon
  export const EyeOff: LucideIcon
  export const Loader: LucideIcon
  export const Loader2: LucideIcon
  export const RotateCw: LucideIcon
  export const RotateCcw: LucideIcon
  export const Maximize: LucideIcon
  export const Minimize: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const MoreVertical: LucideIcon
  export const Grip: LucideIcon
  export const GripVertical: LucideIcon
  export const Wallet: LucideIcon
  export const CreditCard: LucideIcon
  export const Coins: LucideIcon
  export const PiggyBank: LucideIcon
  export const BarChart: LucideIcon
  export const BarChart2: LucideIcon
  export const BarChart3: LucideIcon
  export const LineChart: LucideIcon
  export const PieChart: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowUp: LucideIcon
  export const ArrowDown: LucideIcon
  export const ArrowUpRight: LucideIcon
  export const ArrowDownRight: LucideIcon
  export const ArrowUpLeft: LucideIcon
  export const ArrowDownLeft: LucideIcon
  export const Briefcase: LucideIcon
  export const Building: LucideIcon
  export const Building2: LucideIcon
  export const Package: LucideIcon
  export const Boxes: LucideIcon
  export const Archive: LucideIcon
  export const BookOpen: LucideIcon
  export const FileText: LucideIcon
  export const Clipboard: LucideIcon
  export const Terminal: LucideIcon
  export const Database: LucideIcon
  export const Server: LucideIcon
  export const Cpu: LucideIcon
  export const HardDrive: LucideIcon
  export const Monitor: LucideIcon
  export const Smartphone: LucideIcon
  export const Tablet: LucideIcon
  export const Laptop: LucideIcon
  export const Watch: LucideIcon
  export const Headphones: LucideIcon
  export const Speaker: LucideIcon
  export const Tv: LucideIcon
  export const Cast: LucideIcon
  export const Radio: LucideIcon
  export const Bluetooth: LucideIcon
  export const Rss: LucideIcon
  export const Podcast: LucideIcon
  export const Globe2: LucideIcon
  export const MapPin: LucideIcon
  export const Navigation: LucideIcon
  export const Compass: LucideIcon
  export const Flag: LucideIcon
  export const Bookmark: LucideIcon
  export const Tag: LucideIcon
  export const Tags: LucideIcon
  export const Award: LucideIcon
  export const Trophy: LucideIcon
  export const Medal: LucideIcon
  export const Crown: LucideIcon
  export const Gift: LucideIcon
  export const Cake: LucideIcon
  export const PartyPopper: LucideIcon
  export const Smile: LucideIcon
  export const Frown: LucideIcon
  export const Meh: LucideIcon
  export const Angry: LucideIcon
  export const ThumbsUp: LucideIcon
  export const ThumbsDown: LucideIcon
  export const MessageSquare: LucideIcon
  export const MessagesSquare: LucideIcon
  export const Reply: LucideIcon
  export const Forward: LucideIcon
  export const AtSign: LucideIcon
  export const Paperclip: LucideIcon
  export const Printer: LucideIcon
  export const Scissors: LucideIcon
  export const Pen: LucideIcon
  export const Pencil: LucideIcon
  export const Eraser: LucideIcon
  export const Highlighter: LucideIcon
  export const Palette: LucideIcon
  export const Pipette: LucideIcon
  export const Layers: LucideIcon
  export const Layout: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const LayoutTemplate: LucideIcon
  export const Grid: LucideIcon
  export const Grid2x2: LucideIcon
  export const Grid3x3: LucideIcon
  export const Table: LucideIcon
  export const Table2: LucideIcon
  export const Columns: LucideIcon
  export const Rows: LucideIcon
  export const PanelLeft: LucideIcon
  export const PanelRight: LucideIcon
  export const PanelTop: LucideIcon
  export const PanelBottom: LucideIcon
  export const SidebarOpen: LucideIcon
  export const SidebarClose: LucideIcon
  export const Sidebar: LucideIcon
  export const Square: LucideIcon
  export const Circle: LucideIcon
  export const Triangle: LucideIcon
  export const Pentagon: LucideIcon
  export const Hexagon: LucideIcon
  export const Octagon: LucideIcon
  export const Diamond: LucideIcon
  export const Shapes: LucideIcon
  export const Minus: LucideIcon
  export const Divide: LucideIcon
  export const Equal: LucideIcon
  export const Percent: LucideIcon
  export const Hash2: LucideIcon
  export const Binary: LucideIcon
  export const Sigma: LucideIcon
  export const Infinity: LucideIcon
  export const Pi: LucideIcon
  export const Key: LucideIcon
  export const KeyRound: LucideIcon
  export const Unlock: LucideIcon
  export const ShieldCheck: LucideIcon
  export const ShieldAlert: LucideIcon
  export const ShieldOff: LucideIcon
  export const ShieldQuestion: LucideIcon
  export const Fingerprint: LucideIcon
  export const Scan: LucideIcon
  export const ScanLine: LucideIcon
  export const QrCode: LucideIcon
  export const Barcode: LucideIcon
  export const Contact: LucideIcon
  export const Contact2: LucideIcon
  export const Users2: LucideIcon
  export const UserPlus: LucideIcon
  export const UserMinus: LucideIcon
  export const UserCheck: LucideIcon
  export const UserX: LucideIcon
  export const LogIn: LucideIcon
  export const LogOut: LucideIcon
  export const CircleUser: LucideIcon
  export const UserCircle: LucideIcon
  export const UserCircle2: LucideIcon
  export const Pin: LucideIcon
  export const BellOff: LucideIcon
  export const CheckCircle: LucideIcon
  export const CheckCircle2: LucideIcon
  export const Vote: LucideIcon
  export const ShoppingCart: LucideIcon
  export const Store: LucideIcon
  export const Gavel: LucideIcon
  export const Scale: LucideIcon
  export const Handshake: LucideIcon
  export const FileCheck: LucideIcon
  export const FilePlus: LucideIcon
  export const FileMinus: LucideIcon
  export const FileX: LucideIcon
  export const FileWarning: LucideIcon
  export const FolderOpen: LucideIcon
  export const FolderPlus: LucideIcon
  export const FolderMinus: LucideIcon
  export const FolderCheck: LucideIcon
  export const FolderX: LucideIcon
  export const Inbox: LucideIcon
  export const History: LucideIcon
  export const HistoryIcon: LucideIcon
  export const Timer: LucideIcon
  export const TimerOff: LucideIcon
  export const Alarm: LucideIcon
  export const AlarmClock: LucideIcon
  export const Hourglass: LucideIcon
  export const Stopwatch: LucideIcon
  export const PauseCircle: LucideIcon
  export const PlayCircle: LucideIcon
  export const StopCircle: LucideIcon
  export const SkipBack: LucideIcon
  export const SkipForward: LucideIcon
  export const Rewind: LucideIcon
  export const FastForward: LucideIcon
  export const Shuffle: LucideIcon
  export const Repeat: LucideIcon
  export const Repeat1: LucideIcon
  export const Volume: LucideIcon
  export const Volume1: LucideIcon
  export const VolumeX: LucideIcon
  export const Pause: LucideIcon
  export const Stop: LucideIcon
  export const CircleDot: LucideIcon
  export const Disc: LucideIcon
  export const Disc2: LucideIcon
  export const Disc3: LucideIcon
  export const ListMusic: LucideIcon
  export const ListVideo: LucideIcon
  export const ListPlus: LucideIcon
  export const ListMinus: LucideIcon
  export const ListChecks: LucideIcon
  export const ListOrdered: LucideIcon
  export const ListTodo: LucideIcon
  export const ListTree: LucideIcon
  export const ListFilter: LucideIcon
  export const ListStart: LucideIcon
  export const ListEnd: LucideIcon
  export const ListRestart: LucideIcon
  export const ListX: LucideIcon
  export const ListCollapse: LucideIcon
  export const LayoutList: LucideIcon
  export const Kanban: LucideIcon
  export const KanbanSquare: LucideIcon
  export const Workflow: LucideIcon
  export const GitBranch: LucideIcon
  export const GitCommit: LucideIcon
  export const GitMerge: LucideIcon
  export const GitPullRequest: LucideIcon
  export const GitFork: LucideIcon
  export const GitCompare: LucideIcon
  export const Braces: LucideIcon
  export const Brackets: LucideIcon
  export const CodeXml: LucideIcon
  export const Code2: LucideIcon
  export const FileCode: LucideIcon
  export const FileCode2: LucideIcon
  export const FileJson: LucideIcon
  export const FileJson2: LucideIcon
  export const Bug: LucideIcon
  export const Webhook: LucideIcon
  export const WebhookOff: LucideIcon
  export const Api: LucideIcon
  export const Plug: LucideIcon
  export const Unplug: LucideIcon
  export const Cable: LucideIcon
  export const Usb: LucideIcon
  export const Ethernet: LucideIcon
  export const Router: LucideIcon
  export const Network: LucideIcon
  export const Signal: LucideIcon
  export const SignalHigh: LucideIcon
  export const SignalMedium: LucideIcon
  export const SignalLow: LucideIcon
  export const SignalZero: LucideIcon
  export const WifiOff: LucideIcon
  export const Satellite: LucideIcon
  export const SatelliteDish: LucideIcon
  export const Antenna: LucideIcon
  export const Radio2: LucideIcon
  export const TrendingDown: LucideIcon
  export const ArrowTrendingUp: LucideIcon
  export const ArrowTrendingDown: LucideIcon
  export const Receipt: LucideIcon
  export const ReceiptText: LucideIcon
  export const ScrollText: LucideIcon
  export const Scroll: LucideIcon
  export const NotebookPen: LucideIcon
  export const NotebookText: LucideIcon
  export const Notebook: LucideIcon
  export const Book: LucideIcon
  export const BookA: LucideIcon
  export const BookCheck: LucideIcon
  export const BookCopy: LucideIcon
  export const BookDashed: LucideIcon
  export const BookDown: LucideIcon
  export const BookHeadphones: LucideIcon
  export const BookHeart: LucideIcon
  export const BookImage: LucideIcon
  export const BookKey: LucideIcon
  export const BookLock: LucideIcon
  export const BookMarked: LucideIcon
  export const BookMinus: LucideIcon
  export const BookOpenCheck: LucideIcon
  export const BookOpenText: LucideIcon
  export const BookPlus: LucideIcon
  export const BookText: LucideIcon
  export const BookType: LucideIcon
  export const BookUp: LucideIcon
  export const BookUp2: LucideIcon
  export const BookUser: LucideIcon
  export const BookX: LucideIcon
  export const Library: LucideIcon
  export const LibraryBig: LucideIcon
  export const GraduationCap: LucideIcon
  export const School: LucideIcon
  export const School2: LucideIcon
  export const Landmark: LucideIcon
  export const Factory: LucideIcon
  export const Warehouse: LucideIcon
  export const Fence: LucideIcon
  export const Trees: LucideIcon
  export const TreePine: LucideIcon
  export const TreeDeciduous: LucideIcon
  export const Flower: LucideIcon
  export const Flower2: LucideIcon
  export const Leaf: LucideIcon
  export const Sprout: LucideIcon
  export const Vegan: LucideIcon
  export const Apple: LucideIcon
  export const Cherry: LucideIcon
  export const Citrus: LucideIcon
  export const Grape: LucideIcon
  export const Banana: LucideIcon
  export const Carrot: LucideIcon
  export const Salad: LucideIcon
  export const Sandwich: LucideIcon
  export const Pizza: LucideIcon
  export const Beef: LucideIcon
  export const Egg: LucideIcon
  export const EggFried: LucideIcon
  export const Fish: LucideIcon
  export const Popcorn: LucideIcon
  export const Candy: LucideIcon
  export const Cookie: LucideIcon
  export const Croissant: LucideIcon
  export const Donut: LucideIcon
  export const IceCream: LucideIcon
  export const IceCream2: LucideIcon
  export const CakeSlice: LucideIcon
  export const CupSoda: LucideIcon
  export const GlassWater: LucideIcon
  export const Wine: LucideIcon
  export const Beer: LucideIcon
  export const Coffee: LucideIcon
  export const Milk: LucideIcon
  export const MilkOff: LucideIcon
  export const Soup: LucideIcon
  export const UtensilsCrossed: LucideIcon
  export const Utensils: LucideIcon
  export const ChefHat: LucideIcon
  export const CookingPot: LucideIcon
  export const Refrigerator: LucideIcon
  export const Microwave: LucideIcon
  export const Oven: LucideIcon
  export const Toaster: LucideIcon
  export const Plug2: LucideIcon
  export const PlugZap: LucideIcon
  export const PlugZap2: LucideIcon
  export const BatteryCharging: LucideIcon
  export const BatteryFull: LucideIcon
  export const BatteryLow: LucideIcon
  export const BatteryMedium: LucideIcon
  export const BatteryWarning: LucideIcon
  export const Flame: LucideIcon
  export const Flashlight: LucideIcon
  export const FlashlightOff: LucideIcon
  export const Lightbulb: LucideIcon
  export const LightbulbOff: LucideIcon
  export const Lamp: LucideIcon
  export const LampCeiling: LucideIcon
  export const LampDesk: LucideIcon
  export const LampFloor: LucideIcon
  export const LampWallDown: LucideIcon
  export const LampWallUp: LucideIcon
  export const Sunrise: LucideIcon
  export const Sunset: LucideIcon
  export const Cloudy: LucideIcon
  export const CloudRain: LucideIcon
  export const CloudSnow: LucideIcon
  export const CloudLightning: LucideIcon
  export const CloudFog: LucideIcon
  export const CloudSun: LucideIcon
  export const CloudMoon: LucideIcon
  export const CloudOff: LucideIcon
  export const CloudUpload: LucideIcon
  export const CloudDownload: LucideIcon
  export const Wind: LucideIcon
  export const Tornado: LucideIcon
  export const Rainbow: LucideIcon
  export const Snowflake: LucideIcon
  export const Droplet: LucideIcon
  export const Droplets: LucideIcon
  export const Waves: LucideIcon
  export const ThermometerSun: LucideIcon
  export const ThermometerSnowflake: LucideIcon
  export const Thermometer: LucideIcon
  export const Umbrella: LucideIcon
  export const UmbrellaOff: LucideIcon
  export const Hammer: LucideIcon
  export const Share2: LucideIcon
  export const SlidersHorizontal: LucideIcon
  export const SlidersVertical: LucideIcon
  export const Sliders: LucideIcon
  export const Target: LucideIcon
  export const XCircle: LucideIcon
  export const Trash2: LucideIcon
  export const ShoppingBag: LucideIcon
  export const Crosshair: LucideIcon
  export const Focus: LucideIcon
  export const Move: LucideIcon
  export const Move3d: LucideIcon
  export const MoveHorizontal: LucideIcon
  export const MoveVertical: LucideIcon
  export const MoveDiagonal: LucideIcon
  export const MoveDiagonal2: LucideIcon
  export const Hand: LucideIcon
  export const HandMetal: LucideIcon
  export const Pointer: LucideIcon
  export const PointerOff: LucideIcon
  export const MousePointer: LucideIcon
  export const MousePointer2: LucideIcon
  export const MousePointerClick: LucideIcon
  export const Mouse: LucideIcon
  export const Touchpad: LucideIcon
  export const TouchpadOff: LucideIcon
  export const Joystick: LucideIcon
  export const Gamepad: LucideIcon
  export const Gamepad2: LucideIcon
  export const Dices: LucideIcon
  export const Puzzle: LucideIcon
  export const ToyBrick: LucideIcon
  export const Blocks: LucideIcon
  export const Component: LucideIcon
  export const Combine: LucideIcon
  export const Split: LucideIcon
  export const Merge: LucideIcon
  export const Ungroup: LucideIcon
  export const Group: LucideIcon
  export const Bring: LucideIcon
  export const BringToFront: LucideIcon
  export const SendToBack: LucideIcon
  export const AlignLeft: LucideIcon
  export const AlignCenter: LucideIcon
  export const AlignRight: LucideIcon
  export const AlignJustify: LucideIcon
  export const AlignVerticalJustifyStart: LucideIcon
  export const AlignVerticalJustifyCenter: LucideIcon
  export const AlignVerticalJustifyEnd: LucideIcon
  export const AlignHorizontalJustifyStart: LucideIcon
  export const AlignHorizontalJustifyCenter: LucideIcon
  export const AlignHorizontalJustifyEnd: LucideIcon
  export const AlignStartVertical: LucideIcon
  export const AlignEndVertical: LucideIcon
  export const AlignCenterVertical: LucideIcon
  export const AlignStartHorizontal: LucideIcon
  export const AlignEndHorizontal: LucideIcon
  export const AlignCenterHorizontal: LucideIcon
  export const Baseline: LucideIcon
  export const Bold: LucideIcon
  export const Italic: LucideIcon
  export const Underline: LucideIcon
  export const Strikethrough: LucideIcon
  export const Subscript: LucideIcon
  export const Superscript: LucideIcon
  export const CaseLower: LucideIcon
  export const CaseUpper: LucideIcon
  export const CaseSensitive: LucideIcon
  export const TextCursor: LucideIcon
  export const TextCursorInput: LucideIcon
  export const TextSelect: LucideIcon
  export const Type: LucideIcon
  export const Text: LucideIcon
  export const Heading: LucideIcon
  export const Heading1: LucideIcon
  export const Heading2: LucideIcon
  export const Heading3: LucideIcon
  export const Heading4: LucideIcon
  export const Heading5: LucideIcon
  export const Heading6: LucideIcon
  export const Pilcrow: LucideIcon
  export const Quote: LucideIcon
  export const Indent: LucideIcon
  export const Outdent: LucideIcon
  export const WrapText: LucideIcon
  export const RemoveFormatting: LucideIcon
  export const Space: LucideIcon
  export const Spellcheck: LucideIcon
  export const Languages: LucideIcon
  export const Translate: LucideIcon
  export const MessageCirclePlus: LucideIcon
  export const MessageCircleMinus: LucideIcon
  export const MessageCircleX: LucideIcon
  export const MessageCircleWarning: LucideIcon
  export const MessageCircleQuestion: LucideIcon
  export const MessageCircleHeart: LucideIcon
  export const MessageCircleCode: LucideIcon
  export const MessageCircleDashed: LucideIcon
  export const MessageCircleMore: LucideIcon
  export const MessageCircleOff: LucideIcon
  export const MessageCircleReply: LucideIcon
  export const MessageSquarePlus: LucideIcon
  export const MessageSquareMinus: LucideIcon
  export const MessageSquareX: LucideIcon
  export const MessageSquareWarning: LucideIcon
  export const MessageSquareQuestion: LucideIcon
  export const MessageSquareHeart: LucideIcon
  export const MessageSquareCode: LucideIcon
  export const MessageSquareDashed: LucideIcon
  export const MessageSquareMore: LucideIcon
  export const MessageSquareOff: LucideIcon
  export const MessageSquareReply: LucideIcon
  export const MessageSquareShare: LucideIcon
  export const MessageSquareQuote: LucideIcon
  export const MessageSquareDot: LucideIcon
  export const MessageSquareText: LucideIcon
  export const AlertOctagon: LucideIcon
  export const OctagonAlert: LucideIcon
  export const OctagonPause: LucideIcon
  export const OctagonX: LucideIcon
  export const Ban: LucideIcon
  export const CircleOff: LucideIcon
  export const SlashCircle: LucideIcon
  export const XOctagon: LucideIcon
  export const TriangleAlert: LucideIcon
  export const CircleAlert: LucideIcon
  export const CircleCheck: LucideIcon
  export const CircleX: LucideIcon
  export const CirclePlus: LucideIcon
  export const CircleMinus: LucideIcon
  export const CircleDashed: LucideIcon
  export const CircleDotDashed: LucideIcon
  export const CircleEllipsis: LucideIcon
  export const CircleFadingPlus: LucideIcon
  export const CircleHelp: LucideIcon
  export const CirclePause: LucideIcon
  export const CirclePlay: LucideIcon
  export const CircleStop: LucideIcon
  export const CircleSlash: LucideIcon
  export const CircleSlash2: LucideIcon
  export const SquareCheck: LucideIcon
  export const SquareX: LucideIcon
  export const SquarePlus: LucideIcon
  export const SquareMinus: LucideIcon
  export const SquareDashed: LucideIcon
  export const SquareDashedBottom: LucideIcon
  export const SquareDashedBottomCode: LucideIcon
  export const SquareSlash: LucideIcon
  export const SquareAsterisk: LucideIcon
  export const SquareActivity: LucideIcon
  export const SquareArrowDown: LucideIcon
  export const SquareArrowDownLeft: LucideIcon
  export const SquareArrowDownRight: LucideIcon
  export const SquareArrowLeft: LucideIcon
  export const SquareArrowOutDownLeft: LucideIcon
  export const SquareArrowOutDownRight: LucideIcon
  export const SquareArrowOutUpLeft: LucideIcon
  export const SquareArrowOutUpRight: LucideIcon
  export const SquareArrowRight: LucideIcon
  export const SquareArrowUp: LucideIcon
  export const SquareArrowUpLeft: LucideIcon
  export const SquareArrowUpRight: LucideIcon
  export const SquareBottom: LucideIcon
  export const SquareBottomDashedScissors: LucideIcon
  export const SquareChartGantt: LucideIcon
  export const SquareChevronDown: LucideIcon
  export const SquareChevronLeft: LucideIcon
  export const SquareChevronRight: LucideIcon
  export const SquareChevronUp: LucideIcon
  export const SquareCode: LucideIcon
  export const SquareDivide: LucideIcon
  export const SquareDot: LucideIcon
  export const SquareEqual: LucideIcon
  export const SquareFunction: LucideIcon
  export const SquareGantt: LucideIcon
  export const SquareGanttChart: LucideIcon
  export const SquareKanban: LucideIcon
  export const SquareLibrary: LucideIcon
  export const SquareM: LucideIcon
  export const SquareMenu: LucideIcon
  export const SquareMousePointer: LucideIcon
  export const SquareParking: LucideIcon
  export const SquareParkingOff: LucideIcon
  export const SquarePen: LucideIcon
  export const SquarePercent: LucideIcon
  export const SquarePi: LucideIcon
  export const SquarePilcrow: LucideIcon
  export const SquarePlay: LucideIcon
  export const SquarePower: LucideIcon
  export const SquareRadical: LucideIcon
  export const SquareScissors: LucideIcon
  export const SquareSigma: LucideIcon
  export const SquareSplitHorizontal: LucideIcon
  export const SquareSplitVertical: LucideIcon
  export const SquareStack: LucideIcon
  export const SquareTerminal: LucideIcon
  export const SquareUser: LucideIcon
  export const SquareUserRound: LucideIcon
  export const RectangleHorizontal: LucideIcon
  export const RectangleVertical: LucideIcon
  export const PanelLeftClose: LucideIcon
  export const PanelLeftOpen: LucideIcon
  export const PanelRightClose: LucideIcon
  export const PanelRightOpen: LucideIcon
  export const PanelTopClose: LucideIcon
  export const PanelTopOpen: LucideIcon
  export const PanelBottomClose: LucideIcon
  export const PanelBottomOpen: LucideIcon
  export const MinusCircle: LucideIcon
  export const PlusCircle: LucideIcon
}
