[package]
name = "podai"
version = "0.1.0"
description = "podAI Marketplace: Revolutionary AI Agent Platform"
edition = "2021"
rust-version = "1.79.0"

[lib]
crate-type = ["cdylib"]
name = "podai"
path = "programs/agent-marketplace/src/lib.rs"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
idl-build = ["anchor-lang/idl-build", "spl-account-compression/idl-build"]
anchor-debug = []
no-log-ix-name = []
# 2025 Enhanced Features
ai-agents = []
quantum-resistant = []
advanced-compression = []
cross-chain = []
defi-integration = []

[dependencies]
# Core Solana dependencies - using workspace unified versions (FIXED CONFLICT)
anchor-lang = { workspace = true }
anchor-spl = { version = "0.31.1" }

# Enhanced State Compression with Advanced ZK Features
spl-account-compression = { workspace = true }
spl-concurrent-merkle-tree = { workspace = true }

# Enhanced Token Standards for 2025
spl-token = { version = "8.0.0", features = ["no-entrypoint"], default-features = false }
spl-token-2022 = { version = "9.0.0", features = ["no-entrypoint", "zk-ops"], default-features = false }
spl-associated-token-account = { version = "7.0.0", features = ["no-entrypoint"], default-features = false }

# SPL Token-2022 Metadata Interface - OFFICIAL IMPLEMENTATION
spl-token-metadata-interface = { version = "0.7.0", default-features = false }

# Error handling - using workspace versions
thiserror = { workspace = true }
anyhow = { workspace = true }

# Enhanced cryptographic operations for 2025
blake3 = { workspace = true }
bs58 = { version = "0.5.1", default-features = false, features = ["alloc"] }
sha2 = { version = "0.10.9", default-features = false }
sha3 = { version = "0.10.8", default-features = false }

# AI Agent Integration - Remove explicit borsh to avoid ambiguity
serde = { workspace = true }
serde_json = { version = "1.0.140", default-features = false, features = ["alloc"] }

# Enhanced utilities for 2025
bytemuck = { version = "1.23.1", features = ["derive"] }
log = "0.4.27"

# Cross-chain compatibility - re-enabled with aligned versions
solana-sdk = { workspace = true, optional = true }

[dev-dependencies]
anchor-lang = { version = "0.31.1", features = ["derive"] }
solana-program-test = { workspace = true }  # Re-enabled with workspace version
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
proptest = "1.7.0"

[package.metadata.docs.rs]
all-features = false
no-default-features = true

# Enhanced build configuration for 2025
[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release.build-override]
opt-level = 3
codegen-units = 1