[test]
# Test configuration for Bun
preload = ["./test/setup.ts"]
coverageThreshold = { line = 80, "function" = 80, branch = 70, statement = 80 }
coverageReporter = ["text", "lcov"]
coverageDirectory = "./coverage"

# Test patterns
patterns = [
  "test/**/*.test.ts",
  "test/**/*.test.tsx"
]

# Exclude patterns
exclude = [
  "node_modules",
  "dist",
  "coverage"
]