name: Sync Packages to Individual Repositories

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      sdk-typescript: ${{ steps.changes.outputs.sdk-typescript }}
      sdk-rust: ${{ steps.changes.outputs.sdk-rust }}
      cli: ${{ steps.changes.outputs.cli }}
      core: ${{ steps.changes.outputs.core }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            sdk-typescript:
              - 'packages/sdk-typescript/**'
            sdk-rust:
              - 'packages/sdk-rust/**'
            cli:
              - 'packages/cli/**'
            core:
              - 'packages/core/**'

  sync-typescript:
    needs: detect-changes
    if: needs.detect-changes.outputs.sdk-typescript == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_TOKEN }}
          
      - name: Configure Git
        run: |
          git config user.name "GhostSpeak Bot"
          git config user.email "bot@ghostspeak.dev"
          
      - name: Add TypeScript SDK remote
        run: |
          git remote add typescript-sdk https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/ghostspeak/ghostspeak-typescript-sdk.git || true
          
      - name: Sync TypeScript SDK
        run: |
          git subtree push --prefix=packages/sdk-typescript typescript-sdk main
          
      - name: Update package.json version
        run: |
          echo "⚡ TypeScript SDK synced to individual repository"

  sync-rust:
    needs: detect-changes
    if: needs.detect-changes.outputs.sdk-rust == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_TOKEN }}
          
      - name: Configure Git
        run: |
          git config user.name "GhostSpeak Bot"
          git config user.email "bot@ghostspeak.dev"
          
      - name: Add Rust SDK remote
        run: |
          git remote add rust-sdk https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/ghostspeak/ghostspeak-rust-sdk.git || true
          
      - name: Sync Rust SDK
        run: |
          git subtree push --prefix=packages/sdk-rust rust-sdk main

  sync-cli:
    needs: detect-changes
    if: needs.detect-changes.outputs.cli == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_TOKEN }}
          
      - name: Configure Git
        run: |
          git config user.name "GhostSpeak Bot"
          git config user.email "bot@ghostspeak.dev"
          
      - name: Add CLI remote
        run: |
          git remote add cli https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/ghostspeak/ghostspeak-cli.git || true
          
      - name: Sync CLI
        run: |
          git subtree push --prefix=packages/cli cli main

  notify-success:
    needs: [sync-typescript, sync-rust, sync-cli]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        run: |
          echo "⚡ GhostSpeak packages synced to individual repositories"
          echo "🔮 The protocol distribution network is operational" 